# Generated by Django 5.1.3 on 2025-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrequest',
            name='confirm_password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
