# Generated by Django 5.1.3 on 2024-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='employment_id',
            field=models.ImageField(blank=True, null=True, upload_to='employment_ids/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
