# Generated by Django 5.1.3 on 2025-02-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
